ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "app.tms-applications.com,api.app.tms-applications.com"
  hosts:
    - host: app.tms-applications.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: api.app.tms-applications.com
      paths:
        - path: /
          pathType: Prefix
          service: backend

backend:
  extraEnv:
    - name: POSTGRES_SERVER
      value: db.app.tms-applications.com
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_DB
      value: "app"
    # POSTGRES_USER and POSTGRES_PASSWORD is from external Secrets Store CSI
