apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: kube-system
spec:
  provider: aws
  parameters:
    region: eu-west-2
    objects: |
      - objectName: db-cred
        objectType: secretsmanager
        jmesPath:
            - path: username
              objectAlias: myusername
            - path: password
              objectAlias: mypassword
            - path: smtpPassword
              objectAlias: mysmtpPassword
  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: myusername
          key: k8s-myusername
        - objectName: mypassword
          key: k8s-mypassword
        - objectName: mysmtpPassword
          key: k8s-mysmtpPassword
