"""make agents optional

Revision ID: 2ee05e0c9c9e
Revises: fbf0dffe6c62
Create Date: 2024-12-17 19:53:32.752852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2ee05e0c9c9e'
down_revision = 'fbf0dffe6c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
