"""Add date_of_birth to User model

Revision ID: b38315256fd2
Revises: 0ed16ef4905e
Create Date: 2024-11-21 17:00:02.032492

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b38315256fd2'
down_revision = '0ed16ef4905e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
