name: CI Terraform
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Apply
        run: |
          cd infra/terraform/environments/prod
          terraform apply -var-file=prod.tfvars -auto-approve

      - name: Terraform Output
        run: |
          cd infra/terraform/environments/prod
          terraform output -json > tf_output.json
